name: Default

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build Tests
        run: |
          git submodule update --init --recursive
          sudo apt-get update &&
          sudo apt-get install -y build-essential cmake &&
          cmake -B build -DCMAKE_BUILD_TYPE=MinSizeRel &&
          make -C build -j$(nproc)

      - name: Run Tests
        run: |
          cd build/bin &&
          ./test_device_config_json  && ./test_device_rest_api && ./test_event && ./test_telemetry && ./test_timestamp
